const AboutData = [
 {
    id:1,
    name:" Heading 1 ",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, at.", 
    price:20,
    image:" images/meh1.jpg", 
 },
 {
    id:2,
    name:" Heading 1 ",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, at.", 
    price:20,
    image:" images/meh2.jpg", 
 },
 {
    id:3,
    name:" Heading 1 ",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, at.", 
    price:20,
    image:" images/meh3.jpg", 
 },
 {
    id:4,
    name:" Heading 1 ",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, at.", 
    price:20,
    image:" images/meh4.jpg", 
 },
 {
    id:1,
    name:" Heading 1 ",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, at.", 
    price:20,
    image:" images/meh1.jpg", 
 },
 {
    id:2,
    name:" Heading 1 ",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, at.", 
    price:20,
    image:" images/meh2.jpg", 
 },
 {
    id:3,
    name:" Heading 1 ",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, at.", 
    price:20,
    image:" images/meh3.jpg", 
 },
 {
    id:4,
    name:" Heading 1 ",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, at.", 
    price:20,
    image:" images/meh4.jpg", 
 },
 {
    id:1,
    name:" Heading 1 ",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, at.", 
    price:20,
    image:" images/meh1.jpg", 
 },
 {
    id:2,
    name:" Heading 1 ",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, at.", 
    price:20,
    image:" images/meh2.jpg", 
 },
 {
    id:3,
    name:" Heading 1 ",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, at.", 
    price:20,
    image:" images/meh3.jpg", 
 },
 {
    id:4,
    name:" Heading 1 ",
    description:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Quos, at.", 
    price:20,
    image:" images/meh4.jpg", 
 },
]
export default AboutData;