const ServicesApi = [
    {
        id:1,
        name:"Welcoming arches",
        title:" Welcoming arches 1 ",
        description:" this is Welcoming arches ",
        image:"images/welcomingArches.jpg",
    },
    {
        id:2,
        name:"Welcoming arches",
        title:" Welcoming arches 2 ",
        description:" this is Welcoming arches 2 ",
        image:"images/welcomingArches2.jpg",
    },
    {
        id:3,
        name:"Welcoming arches",
        title:" Welcoming arches 3 ",
        description:" this is Welcoming arches 3 ",
        image:"images/welcomingArches3.jpg",
    },
    {
        id:4,
        name:"Welcoming arches",
        title:" Welcoming arches 4 ",
        description:" this is Welcoming arches  4",
        image:"images/welcomingArches4.jpg",
    },
    {
        id:5,
        name:"Welcoming arches",
        title:" Welcoming arches 5 ",
        description:" this is Welcoming arches 5 ",
        image:"images/welcomingArches5.jpg",
    },
    
    {
        id:6,
        name:"outdoor decoration",
        title:" outdoor decoration 1",
        description:" this is outdoor decoration 1",
        image:" images/outdoor-decor.jpg ",
    },
    {
        id:7,
        name:"outdoor decoration",
        title:" outdoor decoration 2",
        description:" this is outdoor decoration 2 ",
        image:" images/outdoor-decor2.jpg ",
    },
    {
        id:8,
        name:"outdoor decoration",
        title:" outdoor decoration 3",
        description:" this is outdoor decoration 3 ",
        image:" images/outdoor-decor3.jpg ",
    },
    {
        id:9,
        name:"outdoor decoration",
        title:" outdoor decoration 4",
        description:" this is outdoor decoration 4 ",
        image:" images/outdoor-decor4.jpg ",
    },
    {
        id:10,
        name:"outdoor decoration",
        title:" outdoor decoration 5",
        description:" this is outdoor decoration 5 ",
        image:" images/outdoor-decor5.jpg ",
    },
    {
        id:11,
        name:"outdoor decoration",
        title:" outdoor decoration 6",
        description:" this is outdoor decoration 6 ",
        image:" images/outdoor-decor6.jpg ",
    },
    {
        id:12,
        name:"outdoor decoration",
        title:" outdoor decoration 7",
        description:" this is outdoor decoration 7 ",
        image:" images/outdoor-decor7.jpg ",
    },
    {
        id:13,
        name:"outdoor decoration",
        title:" outdoor decoration 8 ",
        description:" this is outdoor decoration 8 ",
        image:" images/home-image1.jpg ",
    },
    // ######################### Walima stages start #################################
    {
        id:14,
        name:"Walima stages",
        title:" Walima stage 1",
        description:" this is Walima stage 1",
        image:" images/walimaStage1.jpg ",
    },
    {
        id:15,
        name:"Walima stages",
        title:" Walima stage 2",
        description:" this is Walima stage 2",
        image:" images/walimaStage2.jpg ",
    },
    {
        id:16,
        name:"Walima stages",
        title:" Walima stage 3",
        description:" this is Walima stage 3",
        image:" images/walimaStage3.jpg ",
    },
    {
        id:17,
        name:"Walima stages",
        title:" Walima stage 4",
        description:" this is Walima stage 4",
        image:" images/walimaStage4.jpg ",
    },
    {
        id:18,
        name:"Walima stages",
        title:" Walima stage 5",
        description:" this is Walima stage 5",
        image:" images/walimaStage5.jpg ",
    },
    {
        id:19,
        name:"Walima stages",
        title:" Walima stage 6",
        description:" this is Walima stage 6",
        image:" images/walimaStage6.jpg ",
    },
    {
        id:20,
        name:"Walima stages",
        title:" Walima stage 7",
        description:" this is Walima stage 7",
        image:" images/walimaStage7.jpg ",
    },
    // ############################ Bed decore start ###########################################

 
    {
        id:21,
        name:" Bed decoration",
        title:" Bed decoration fresh 1 ",
        description:" this is Bed decoration fresh 1 ",
        image:" images/bed1.jpg ",
    },
    {
        id:22,
        name:" Bed decoration",
        title:" Bed decoration fresh 2 ",
        description:" this is Bed decoration fresh 2 ",
        image:" images/bed2.jpg ",
    },
    {
        id:23,
        name:" Bed decoration",
        title:" Bed decoration fresh 3 ",
        description:" this is Bed decoration fresh 3 ",
        image:" images/bed3.jpg ",
    },
    {
        id:24,
        name:" Bed decoration",
        title:" Bed decoration fresh 4 ",
        description:" this is Bed decoration fresh 4 ",
        image:" images/bed4.jpg ",
    },
    {
        id:25,
        name:" Bed decoration",
        title:" Bed decoration fresh 5 ",
        description:" this is Bed decoration fresh 5 ",
        image:" images/bed5.jpg ",
    },
    {
        id:26,
        name:" Bed decoration",
        title:" Bed decoration fresh 6 ",
        description:" this is Bed decoration fresh 6 ",
        image:" images/bed6.jpg ",
    },
    {
        id:27,
        name:" Bed decoration",
        title:" Bed decoration fresh 7 ",
        description:" this is Bed decoration fresh 7 ",
        image:" images/bed7.jpg ",
    },
    {
        id:28,
        name:" Bed decoration",
        title:" Bed decoration fresh 8 ",
        description:" this is Bed decoration fresh 8 ",
        image:" images/bed8.jpg ",
    },
    // ############################### Artificial stages ###########################
    {
        id:29,
        name:" Artificial stages ",
        title:" Artificial stage 1 ",
        description:" this is Artificial stage 1 ",
        image:" images/artificial1.jpg ",
    },
    {
        id:30,
        name:" Artificial stages ",
        title:" Artificial stage 2 ",
        description:" this is Artificial stage 2 ",
        image:" images/artificial2.jpg ",
    },
    {
        id:31,
        name:" Artificial stages ",
        title:" Artificial stage 3 ",
        description:" this is Artificial stage 3 ",
        image:" images/artificial3.jpg ",
    },
    {
        id:32,
        name:" Artificial stages ",
        title:" Artificial stage 4 ",
        description:" this is Artificial stage 4 ",
        image:" images/artificial4.jpg ",
    },
    {
        id:33,
        name:" Artificial stages ",
        title:" Artificial stage 5 ",
        description:" this is Artificial stage 5 ",
        image:" images/artificial5.jpg ",
    },
    {
        id:34,
        name:" Artificial stages ",
        title:" Artificial stage 6 ",
        description:" this is Artificial stage 6 ",
        image:" images/artificial6.jpg ",
    },
    {
        id:35,
        name:" Artificial stages ",
        title:" Artificial stage 7 ",
        description:" this is Artificial stage 7 ",
        image:" images/artificial7.jpg ",
    },
    {
        id:36,
        name:" Artificial stages ",
        title:" Artificial stage 8 ",
        description:" this is Artificial stage 8 ",
        image:" images/artificial8.jpg ",
    },
    {
        id:37,
        name:" Artificial stages ",
        title:" Artificial stage 9 ",
        description:" this is Artificial stage 9 ",
        image:" images/artificial9.jpg ",
    },
    // ############################ Birthday stages ################################
    {
        id:38,
        name:" Birthday Stages",
        title:" Birthday Stage 1 ",
        description:" this is Birthday Stage 1 ",
        image:" images/bd1.jpg ",
    },
    {
        id:39,
        name:" Birthday Stages",
        title:" Birthday Stage 2 ",
        description:" this is Birthday Stage 2 ",
        image:" images/bd2.jpg ",
    },
    {
        id:40,
        name:" Birthday Stages",
        title:" Birthday Stage 3 ",
        description:" this is Birthday Stage 3 ",
        image:" images/bd3.jpg ",
    },
    {
        id:41,
        name:" Birthday Stages",
        title:" Birthday Stage 4 ",
        description:" this is Birthday Stage 4 ",
        image:" images/bd4.jpg ",
    },
    {
        id:42,
        name:" Birthday Stages",
        title:" Birthday Stage 5 ",
        description:" this is Birthday Stage 5 ",
        image:" images/bd5.jpg ",
    },
    {
        id:43,
        name:" Birthday Stages",
        title:" Birthday Stage 6 ",
        description:" this is Birthday Stage 6 ",
        image:" images/bd6.jpg ",
    },
    // #################################### Car decoration #########################################
    {
        id:44,
        name:" Car decoration",
        title:" Car decoration 1 ",
        description:" this is Car decoration 1 ",
        image:" images/car1.jpg ",
    },
    {
        id:45,
        name:" Car decoration",
        title:" Car decoration 2 ",
        description:" this is Car decoration 2 ",
        image:" images/car2.jpg ",
    },
    {
        id:46,
        name:" Car decoration",
        title:" Car decoration 3 ",
        description:" this is Car decoration 3 ",
        image:" images/car3.jpg ",
    },
    {
        id:47,
        name:" Car decoration",
        title:" Car decoration 4 ",
        description:" this is Car decoration 4 ",
        image:" images/car4.jpg ",
    },
    {
        id:48,
        name:" Car decoration",
        title:" Car decoration 5 ",
        description:" this is Car decoration 5 ",
        image:" images/car5.jpg ",
    },
    {
        id:49,
        name:" Car decoration",
        title:" Car decoration 6 ",
        description:" this is Car decoration 6 ",
        image:" images/car6.jpg ",
    },
    {
        id:50,
        name:" Car decoration",
        title:" Car decoration 7 ",
        description:" this is Car decoration 7 ",
        image:" images/car7.jpg ",
    },
    {
        id:51,
        name:" Car decoration",
        title:" Car decoration 8 ",
        description:" this is Car decoration 8 ",
        image:" images/car8.jpg ",
    },
    {
        id:52,
        name:" Car decoration",
        title:" Car decoration 9 ",
        description:" this is Car decoration 9 ",
        image:" images/car9.jpg ",
    },
    {
        id:53,
        name:" Car decoration",
        title:" Car decoration 10 ",
        description:" this is Car decoration 10 ",
        image:" images/car10.jpg ",
    },
    // ##################################### Mehndi stages ################################
    {
        id:54,
        name:" Mehandi stages",
        title:"  Mehandi stage 1 ",
        description:" this is  Mehandi stage 1 ",
        image:" images/meh1.jpg ",
    },
    {
        id:55,
        name:" Mehandi stages",
        title:"  Mehandi stage 2 ",
        description:" this is  Mehandi stage 2 ",
        image:" images/meh2.jpg ",
    },
    {
        id:56,
        name:" Mehandi stages",
        title:"  Mehandi stage 3 ",
        description:" this is  Mehandi stage 3 ",
        image:" images/meh3.jpg ",
    },
    {
        id:57,
        name:" Mehandi stages",
        title:"  Mehandi stage 4 ",
        description:" this is  Mehandi stage 4 ",
        image:" images/meh4.jpg ",
    },
    {
        id:58,
        name:" Mehandi stages",
        title:"  Mehandi stage 5 ",
        description:" this is  Mehandi stage 5 ",
        image:" images/meh5.jpg ",
    },
    {
        id:59,
        name:" Mehandi stages",
        title:"  Mehandi stage 6 ",
        description:" this is  Mehandi stage 6 ",
        image:" images/meh6.jpg ",
    },
    {
        id:14,
        name:" event photography",
        title:"  photography 1 ",
        description:" this is  photography 1 ",
        image:" images/home-image1.jpg ",
    },
    {
        id:15,
        name:" event photography",
        title:"  photography 2 ",
        description:" this is  photography 2 ",
        image:" images/home-image1.jpg ",
    },
    {
        id:16,
        name:" event photography",
        title:"  photography 3 ",
        description:" this is  photography 3 ",
        image:" images/home-image1.jpg ",
    },
]
export default ServicesApi;